### PR TITLE
fix: update url

### LINKED ISSUE #4: Fix Lists page redirecting to homepage

### PR DESCRIPTION
**Pull request by safiurrehman96**

### CODE REVIEW

File: src/constants/api-params.ts [hunk 1]
```diff
@@ -1,3 +1,3 @@
 export const API_URL = "https://api.joinsafedeal.com";
-export const LISTS_URL = "https://joinsafedeal.com/lists";
+export const LISTS_URL = "https://www.joinsafedeal.com/lists";
```
Comment (Carmageddon) [inline src/constants/api-params.ts:2]: This feels like the wrong fix, the fix should be to make the domain work without www as well, www subdomain should only be an alias, it should work without it.

Thoughts, @obender ?

Comment (safiurrehman96) [reply src/constants/api-params.ts:2]: True. We need to add an A record for www pointing towards @ in DNS settings. Then it should be able to handle request without www. Right now it permanently redirects all the requests without www to homepage. I had to do this to make lists work for now.

**Comment by obender** [comment]
Approved
